# Generated by Django 5.1.3 on 2025-07-22 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_borrower_borrow"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Borrow",
            new_name="BookBorrowed",
        ),
    ]
