# Generated by Django 5.1.3 on 2025-07-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_borrow_bookborrowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookborrowed",
            name="active_loan",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="card_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
