# Generated by Django 5.1.3 on 2025-07-22 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_bookborrowed_active_loan_alter_book_isbn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookborrowed",
            name="borrower",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.borrower",
            ),
        ),
    ]
