# Generated by Django 5.1.3 on 2025-07-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_bookborrowed_borrower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="card_number",
            field=models.CharField(max_length=255),
        ),
    ]
