# Generated by Django 5.1.3 on 2025-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_borrower_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="card_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
