# Generated by Django 5.1.3 on 2025-07-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_borrower_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookborrowed",
            name="duration",
            field=models.DateField(),
        ),
    ]
